# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  Indentation:
    active: false
  FinalNewline:
    active: false
  ParameterListWrapping:
    active: false
  MaximumLineLength:
    active: false
  NoBlankLineBeforeRbrace:
    active: false
  SpacingAroundColon:
    active: false
  NoUnusedImports:
    active: false
  NoConsecutiveBlankLines:
    active: false
  NoWildcardImports:
    active: false
  SpacingAroundComma:
    active: false
empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true
style:
  NewLineAtEndOfFile:
    active: false
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: false
  MagicNumber:
    active: false
  WildcardImport:
    active: false
